### ISSUE TITLE
A little suggest

### ISSUE THREAD

**Issue by aodzip** [Soft-Wolf/Anti-Advert#1]
As I remember , if you use stripos instead of strpos , it can ignore it is an caps letter or a small letter
https://github.com/Soft-Wolf/Anti-Advert/blob/master/src/MasterWolf/Main.php#L40

**Comment by aodzip** [comment]
You can get some info here
http://php.net/manual/en/function.stripos.php

**Comment by MasterWolf** [comment]
@aodzip thanks for info! I will look on it :)

**Comment by MasterWolf** [comment]
@aodzip join the team if you want :)
